# Generated by Django 4.2.9 on 2024-01-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=365)),
                ('txn_id', models.CharField(default=transactions.models._generate_txn_id, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('started', 'started'), ('verifying', 'verifying'), ('transacting', 'transacting'), ('completed', 'completed'), ('closed', 'closed'), ('failed', 'failed')], default='scheduled', max_length=36)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
